### ISSUE TITLE
Test making a github contribution

### ISSUE THREAD

**Issue by healthactuary** [validatehealth/actuary#6]
- [x] Clone this repo to your local computer
- [x] Create a development branch specific to your task. You can be working on multiple branches at once. You'd call dev-ssk.
- [x] Add a one-line comment to one of the python files on your local computer
- [x] Commit the change and make a comment for the commit
- [x] Push your branch
- [x] Create a pull request on GitHub.com for @healthactuary to review

**Comment by healthactuary** [comment]
@SidKasi do you have a status for this GHI?

**Comment by SidKasi** [comment]
@healthactuary Yes

**Comment by healthactuary** [comment]
@SidKasi awesome, thanks for the update!

**Comment by healthactuary** [comment]
@SidKasi as you go along, check off the items above. You should be able to try cloning this repository to your local computer. if you're able to then check of the box above in the first comment. if not, we can do a screenshare and go through how to clone a repo. Just let me know!

**Comment by healthactuary** [comment]
@SidKasi looks good. For the last step (Create a pull request on GitHub.com for @healthactuary to review), do:

1. Go to https://github.com/validatehealth/actuary/pulls
2. Click create pull request
3. Select your branch
4. Click create pull request
5. Add @healthactuary as the reviewer

Then I'll review and merge into the main code base unless there are things to edit before merging with the master branch.

**Comment by healthactuary** [comment]
Successfully merged pull req https://github.com/validatehealth/actuary/pull/7 having the comment
